# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rent',
                'doc_host': 'https://gilad-rubin.github.io',
                'git_url': 'https://github.com/gilad-rubin/rent',
                'lib_path': 'rent'},
  'syms': {'rent.core': {'rent.core.foo': ('core.html#foo', 'rent/core.py')}}}
