# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rent',
                'doc_host': 'https://gilad-rubin.github.io',
                'git_url': 'https://github.com/gilad-rubin/rent',
                'lib_path': 'rent'},
  'syms': { 'rent.core': {'rent.core.foo': ('core.html#foo', 'rent/core.py')},
            'rent.new_way': { 'rent.new_way.avg_3wk_spend': ('archive/new_way.html#avg_3wk_spend', 'rent/new_way.py'),
                              'rent.new_way.spend_mean': ('archive/new_way.html#spend_mean', 'rent/new_way.py'),
                              'rent.new_way.spend_per_signup': ('archive/new_way.html#spend_per_signup', 'rent/new_way.py'),
                              'rent.new_way.spend_std_dev': ('archive/new_way.html#spend_std_dev', 'rent/new_way.py'),
                              'rent.new_way.spend_zero_mean': ('archive/new_way.html#spend_zero_mean', 'rent/new_way.py'),
                              'rent.new_way.spend_zero_mean_unit_variance': ( 'archive/new_way.html#spend_zero_mean_unit_variance',
                                                                              'rent/new_way.py')},
            'rent.transformations': { 'rent.transformations.is_half_bath': ('transformations.html#is_half_bath', 'rent/transformations.py'),
                                      'rent.transformations.load_data': ('transformations.html#load_data', 'rent/transformations.py')}}}