# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/archive/new_way.ipynb.

# %% auto 0
__all__ = ['avg_3wk_spend', 'spend_per_signup', 'spend_mean', 'spend_zero_mean', 'spend_std_dev', 'spend_zero_mean_unit_variance']

# %% ../nbs/archive/new_way.ipynb 3
import pandas as pd

# %% ../nbs/archive/new_way.ipynb 4
def avg_3wk_spend(spend: pd.Series) -> pd.Series: 
    """Rolling 4 day average spend."""
    return spend.rolling(4).mean()

# %% ../nbs/archive/new_way.ipynb 5
def spend_per_signup(spend: pd.Series, signups: pd.Series) -> pd.Series:
    """The cost per signup in relation to spend."""
    return spend / signups

# %% ../nbs/archive/new_way.ipynb 6
@tag(cache="pkl")
def spend_mean(spend: pd.Series) -> float:
    """Shows function creating a scalar. In this case it computes the mean of the entire column."""
    return spend.mean()

# %% ../nbs/archive/new_way.ipynb 7
def spend_zero_mean(spend: pd.Series, spend_mean: float) -> pd.Series:
    """Shows function that takes a scalar. In this case to zero mean spend."""
    return spend - spend_mean

# %% ../nbs/archive/new_way.ipynb 8
def spend_std_dev(spend: pd.Series) -> float:
    """Function that computes the standard deviation of the spend column."""
    return spend.std()

# %% ../nbs/archive/new_way.ipynb 9
def spend_zero_mean_unit_variance(spend_zero_mean: pd.Series, spend_std_dev: float) -> pd.Series:
    """Function showing one way to make spend have zero mean and unit variance."""
    return spend_zero_mean / spend_std_dev
